### ISSUE TITLE
The function call for gene.hidden generation is commented

### ISSUE THREAD

**Issue by Simon-Huang1** [aksinghal5590/nest_drugcell#7]
The line 39 of rlipp_calculator.py is commented out (#self.create_gene_hidden_files()). Is the gene hidden no longer required for rlipp calculation or is the gene.hidden generated elsewhere for newer version of nest_drugcell.

**Comment by aksinghal5590** [comment]
create_gene_hidden_files() needs to be run only once. Uncomment it to generate the gene hidden files.
