### ISSUE TITLE
data request

### ISSUE THREAD

**Issue by phdstudent-oje** [aksinghal5590/nest_drugcell#8]
Dear @aksinghal5590, 

Hi I'm Oh. 
Thanks for this great work.

Could I get updated version (v2) of the model, and following data?
drugcell_v2.pt (model)
cell2ind.txt (1258 cell lines)
cell2mutation.txt (mutation data of 128 cell lines)
drug2fingerprint.txt (fingerprint of 888 drugs)
drug2ind.txt (id of 888 drugs)
drugcell_all.txt (692,589 pairs)
drugcell_ont.txt (ontology of included genes)
gene2ind.txt (included genes)

Many thanks. 

Best, 

Oh.

**Comment by aksinghal5590** [comment]
> 

Hi Oh,

Sorry, this is not a published version and so this is not the correct repository for going through the drugcell project. Here's the link to the [original](https://github.com/idekerlab/DrugCell).
